-- Catalogue des pièces de rechange : liste fournie par l'exploitant le
-- 08/10/2026 (bordereau GE, électricité, éclairage et balisage, climatisation,
-- shelter, cuves, solaire et hybride), 114 lignes, plus les consommables
-- d'entretien GE (filtres à air, à gasoil, à huile ; huile moteur au litre ;
-- courroie alternateur) et le cadenas inox.
-- La batterie 12V 70/80/100 Ah est découpée en trois lignes : une saisie
-- « Batterie 12V 100Ah » se rattache ainsi à SA capacité.
--
-- Libellés repris tels quels, aux fautes de frappe près (accents, « soufflant »,
-- « silicone », « µF »). Les PRESTATIONS de la liste (SWAP de GE, entretien et
-- remplacements complets de climatiseur, reprises de tôlerie, socles…) portent
-- l'unité « forfait » pour se distinguer des pièces à l'unité.
--
-- NON DESTRUCTIF : une ligne est ignorée si le catalogue a déjà le même code OU
-- le même libellé normalisé (casse, accents, séparateurs : la normalisation du
-- rapprochement, utils normaliserPiece). Une pièce saisie à la main avant ce
-- déploiement est donc gardée telle quelle, sans doublon.

INSERT INTO "pieces_ref" ("id", "code", "libelle", "categorie", "unite")
SELECT gen_random_uuid()::text, v.code, v.libelle, v.categorie, v.unite
FROM (VALUES
  ('BATTERIE_12V_70AH', 'Batterie 12V 70 Ah', 'BATTERIE', 'unité'),
  ('BATTERIE_12V_80AH', 'Batterie 12V 80 Ah', 'BATTERIE', 'unité'),
  ('BATTERIE_12V_100AH', 'Batterie 12V 100 Ah', 'BATTERIE', 'unité'),
  ('GE_SD_NEZ_INJECTEUR', 'SD Nez d''injecteur', 'GE', 'unité'),
  ('GE_INJECTEUR', 'Injecteur (une unité par GE)', 'GE', 'unité'),
  ('GE_FILTRE_AIR', 'Filtre à air', 'GE', 'unité'),
  ('GE_FILTRE_GASOIL', 'Filtre à gasoil', 'GE', 'unité'),
  ('GE_FILTRE_HUILE', 'Filtre à huile', 'GE', 'unité'),
  ('GE_HUILE_MOTEUR_15W40', 'Huile moteur 15W40', 'GE', 'litre'),
  ('GE_TUYAU_ALIMENTATION', 'Tuyau d''alimentation', 'GE', 'mètre'),
  ('GE_TUYAU_GRAISSAGE', 'Tuyau de graissage', 'GE', 'unité'),
  ('GE_TUYAU_FLEXIBLE', 'Tuyau flexible', 'GE', 'mètre'),
  ('GE_BECS_INJECTEUR', 'Becs d''injecteur', 'GE', 'unité'),
  ('GE_TURBO_SOUFFLANT', 'Turbo soufflant', 'GE', 'unité'),
  ('GE_VANNES_THERMOSTATIQUES', 'Vannes thermostatiques', 'GE', 'unité'),
  ('GE_FAISCEAUX_RADIATEUR', 'Faisceaux du radiateur', 'GE', 'unité'),
  ('GE_COLLECTEURS_RADIATEUR', 'Collecteurs du radiateur', 'GE', 'unité'),
  ('GE_COLLIERS', 'Colliers', 'GE', 'unité'),
  ('GE_ECROUS', 'Écrous', 'GE', 'unité'),
  ('GE_RONDELLES', 'Rondelles', 'GE', 'unité'),
  ('GE_BOULONS', 'Boulons', 'GE', 'unité'),
  ('GE_COLLECTEURS_ECHAPPEMENT', 'Collecteurs d''échappement', 'GE', 'unité'),
  ('GE_SORTIES_COLLECTEURS_ECHAPPEMENT', 'Sorties de collecteurs d''échappement', 'GE', 'unité'),
  ('GE_REGULATEURS_TENSION', 'Régulateurs de tension', 'GE', 'unité'),
  ('GE_DEMARREUR_12V', 'Démarreur 12V', 'GE', 'unité'),
  ('GE_DEMARREUR_24V', 'Démarreur 24V', 'GE', 'unité'),
  ('GE_BOBINE', 'Bobine', 'GE', 'unité'),
  ('RELAIS_AUXILIAIRES_30_70VDC', 'Relais auxiliaires 30/70V DC', 'AUTRE', 'unité'),
  ('DISJ_10_25A_1P_N', 'Disjoncteur de 10 à 25 A 1P+N', 'AUTRE', 'unité'),
  ('DISJ_10_25A_TETRA', 'Disjoncteur de 10 à 25 A tétrapolaire', 'AUTRE', 'unité'),
  ('DISJ_40_63A_TETRA', 'Disjoncteur de 40 à 63 A tétrapolaire', 'AUTRE', 'unité'),
  ('DISJ_TETRA_DIFFERENTIEL', 'Disjoncteur tétrapolaire différentiel', 'AUTRE', 'unité'),
  ('GE_COURROIE_ALTERNATEUR', 'Courroie alternateur', 'GE', 'unité'),
  ('GE_COURROIE_DISTRIBUTION', 'Courroie de distribution', 'GE', 'unité'),
  ('GE_BOUGIE', 'Bougie', 'GE', 'unité'),
  ('GE_ELECTROVANNE_ARRET', 'Électrovanne d''arrêt', 'GE', 'unité'),
  ('GE_POMPE_EAU', 'Pompe à eau', 'GE', 'unité'),
  ('GE_POMPE_ALIMENTAIRE_FUEL', 'Pompe alimentaire fuel', 'GE', 'unité'),
  ('GE_CARTE_DSE_4520', 'Carte de commande DSE 4520', 'GE', 'unité'),
  ('GE_CARTE_DSE_7320', 'Carte de commande DSE 7320', 'GE', 'unité'),
  ('GE_CARTE_INTELECT_AMF', 'Carte de commande Intelect AMF', 'GE', 'unité'),
  ('GE_REGULATEUR_ALTERNATEUR_CHARGE', 'Régulateur d''alternateur de charge', 'GE', 'unité'),
  ('GE_CHARGEUR_BATTERIE_220V_12VDC', 'Chargeur de batterie 220V/12VDC', 'GE', 'unité'),
  ('GE_ROULEMENT_ARRIERE', 'Roulement arrière', 'GE', 'unité'),
  ('CABLE_RO2V_4X16', 'Câble RO2V 4x16 mm²', 'CABLE', 'mètre'),
  ('CABLE_RO2V_5X2_5', 'Câble RO2V 5x2,5 mm²', 'CABLE', 'mètre'),
  ('CABLE_U1000_R2V_4X10', 'Câble U1000 R2V 4x10 mm²', 'CABLE', 'mètre'),
  ('CONTACTEUR_AUXILIAIRE_3F_2O', 'Contacteur auxiliaire 3F+2O', 'AUTRE', 'unité'),
  ('CONTACTEUR_4X40A', 'Contacteur 4x40A', 'AUTRE', 'unité'),
  ('RELAIS_12V_30_70A', 'Relais 12V 30/70A', 'AUTRE', 'unité'),
  ('RELAIS_12V_15_30A', 'Relais 12V 15-30A', 'AUTRE', 'unité'),
  ('RELAIS_12V_70A', 'Relais 12V 70A', 'AUTRE', 'unité'),
  ('DISJ_TETRA_COMPTEUR_CEET_15_60A', 'Disjoncteur tétrapolaire compteur CEET 15-60A', 'AUTRE', 'unité'),
  ('DISJ_TETRA_COMPTEUR_CEET_10_30A', 'Disjoncteur tétrapolaire compteur CEET 10-30A', 'AUTRE', 'unité'),
  ('ECL_TUBE_FLUO_0_60M', 'Tube fluorescent 0,60 m', 'AUTRE', 'unité'),
  ('ECL_TUBE_FLUO_1_20M', 'Tube fluorescent 1,20 m', 'AUTRE', 'unité'),
  ('ECL_LAMPE_ECONOMIQUE_11W', 'Lampe économique 11 W', 'AUTRE', 'unité'),
  ('ECL_TUBE_NEON_0_60M', 'Tube néon 0,60 m', 'AUTRE', 'unité'),
  ('ECL_REGLETTE_0_60M_SIMPLE', 'Réglette complète 0,60 m simple', 'AUTRE', 'unité'),
  ('ECL_REGLETTE_0_60M_ETANCHE', 'Réglette complète 0,60 m étanche', 'AUTRE', 'unité'),
  ('ECL_TUBE_NEON_1_20M', 'Tube néon 1,20 m', 'AUTRE', 'unité'),
  ('ECL_REGLETTE_1_20M_SIMPLE', 'Réglette complète 1,20 m simple', 'AUTRE', 'unité'),
  ('ECL_REGLETTE_1_20M_ETANCHE_MONO', 'Réglette complète 1,20 m étanche mono', 'AUTRE', 'unité'),
  ('ECL_REGLETTE_1_20M_ETANCHE_DUO', 'Réglette complète 1,20 m étanche duo', 'AUTRE', 'unité'),
  ('BALISE_COMPLETE', 'Balise complète avec tous les accessoires', 'AUTRE', 'unité'),
  ('ARMAFLEX_METRE', 'Remplacement d''armaflex au mètre', 'CLIMATISEUR', 'mètre'),
  ('BALISE_REMPLACEMENT_LAMPES', 'Remplacement des lampes de balise', 'AUTRE', 'site'),
  ('SWAP_GE_URBAIN_LOME', 'SWAP de GE urbain Lomé', 'GE', 'forfait'),
  ('SWAP_GE_HU_MARITIME', 'SWAP de GE hors urbain Région Maritime', 'GE', 'forfait'),
  ('SWAP_GE_HU_PLATEAUX', 'SWAP de GE hors urbain Région des Plateaux', 'GE', 'forfait'),
  ('SWAP_GE_HU_CENTRALE_KARA', 'SWAP de GE hors urbain Région Centrale & Kara', 'GE', 'forfait'),
  ('SWAP_GE_HU_SAVANES', 'SWAP de GE hors urbain Région des Savanes', 'GE', 'forfait'),
  ('PATE_SILICONE', 'Pâte silicone', 'AUTRE', 'unité'),
  ('CLIM_INSTALLATION_SPLITS', 'Installation de splits', 'CLIMATISEUR', 'forfait'),
  ('CLIM_GAZ_R22', 'Appoint de gaz fréon 22', 'CLIMATISEUR', 'kg'),
  ('CLIM_GAZ_R410', 'Appoint de gaz R410', 'CLIMATISEUR', 'kg'),
  ('CLIM_SPLIT_1_5CV_R410', 'Climatiseur split 1,5 CV au gaz R410', 'CLIMATISEUR', 'unité'),
  ('CLIM_SPLIT_2CV_R410', 'Climatiseur split 2 CV au gaz R410', 'CLIMATISEUR', 'unité'),
  ('CLIM_SPLIT_3CV_R410', 'Climatiseur split 3 CV au gaz R410', 'CLIMATISEUR', 'unité'),
  ('CLIM_RACCORDS_SOUDURE', 'Raccords et matériel de soudure', 'CLIMATISEUR', 'unité'),
  ('CLIM_PLAQUETTE_COMMANDE', 'Plaquette (carte électronique de commande)', 'CLIMATISEUR', 'unité'),
  ('CADENAS_INOX', 'Cadenas inox', 'AUTRE', 'unité'),
  ('SHELTER_PORTE_SERRURE', 'Réparation de la porte et de la serrure du shelter', 'AUTRE', 'forfait'),
  ('DISJ_BRANCHEMENT_CEET_10_30A', 'Disjoncteur de branchement général CEET 10/30A 500mA tétrapolaire', 'AUTRE', 'unité'),
  ('CLIM_ENTRETIEN_COMPLET', 'Entretien complet d''un climatiseur', 'CLIMATISEUR', 'forfait'),
  ('SHELTER_TOLERIE_PEINTURE', 'Reprise de la tôlerie et peinture antirouille', 'AUTRE', 'forfait'),
  ('CLIM_REMPL_SPLIT_1_5CV', 'Fourniture et remplacement complet d''un split de 1,5 CV au gaz R410', 'CLIMATISEUR', 'forfait'),
  ('CLIM_REMPL_CONDENSEUR_1_5CV', 'Fourniture et remplacement d''un condenseur 1,5 CV au gaz R410', 'CLIMATISEUR', 'forfait'),
  ('CLIM_REMPL_EVAPORATEUR_1_5CV', 'Fourniture et remplacement d''un évaporateur de 1,5 CV au gaz R410', 'CLIMATISEUR', 'forfait'),
  ('CLIM_REMPL_SPLIT_2CV', 'Fourniture et remplacement complet d''un split de 2 CV au gaz R410', 'CLIMATISEUR', 'forfait'),
  ('CLIM_REMPL_CONDENSEUR_2CV', 'Fourniture et remplacement d''un condenseur 2 CV au gaz R410', 'CLIMATISEUR', 'forfait'),
  ('CLIM_REMPL_EVAPORATEUR_2CV', 'Fourniture et remplacement d''un évaporateur de 2 CV au gaz R410', 'CLIMATISEUR', 'forfait'),
  ('CLIM_REMPL_SPLIT_3CV', 'Fourniture et remplacement complet d''un split de 3 CV au gaz R410', 'CLIMATISEUR', 'forfait'),
  ('CLIM_REMPL_CONDENSEUR_3CV', 'Fourniture et remplacement d''un condenseur 3 CV au gaz R410', 'CLIMATISEUR', 'forfait'),
  ('CLIM_REMPL_EVAPORATEUR_3CV', 'Fourniture et remplacement d''un évaporateur de 3 CV au gaz R410', 'CLIMATISEUR', 'forfait'),
  ('CLIM_RECHERCHE_FUITE', 'Recherche et réparation de fuite', 'CLIMATISEUR', 'forfait'),
  ('CLIM_CONSOMMABLES_ENTRETIEN', 'Fourniture des consommables d''entretien (soude, savon liquide)', 'CLIMATISEUR', 'forfait'),
  ('CLIM_CONDENSATEUR_30_50UF', 'Contrôle et remplacement de condensateur de 30 à 50 µF', 'CLIMATISEUR', 'unité'),
  ('CLIM_CONDENSATEUR_1_5UF', 'Contrôle et remplacement de condensateur de 1 à 5 µF', 'CLIMATISEUR', 'unité'),
  ('CLIM_COMPRESSEUR_1_5CV', 'Contrôle et remplacement de compresseur de 1,5 CV', 'CLIMATISEUR', 'unité'),
  ('CLIM_MOTEUR_CONDENSEUR_HELICE', 'Contrôle et remplacement de moteur de condenseur et hélice', 'CLIMATISEUR', 'unité'),
  ('CLIM_COURROIE', 'Contrôle et remplacement de courroie au modèle', 'CLIMATISEUR', 'unité'),
  ('CLIM_FACADE_BAC_ECOULEMENT', 'Remplacement de façade ou bac d''écoulement', 'CLIMATISEUR', 'unité'),
  ('CLIM_MOTEUR_EVAPORATEUR_TURBINE', 'Remplacement de moteur d''évaporateur et turbine', 'CLIMATISEUR', 'unité'),
  ('CLIM_ARMAFLEX', 'Fourniture et remplacement de l''armaflex', 'CLIMATISEUR', 'forfait'),
  ('CLIM_PLATINE_TELECOMMANDE', 'Dépannage de platine électronique / remplacement de platine / télécommande', 'CLIMATISEUR', 'forfait'),
  ('CLIM_SOCLE_BETON_CONDENSEUR', 'Confection de socle en béton pour condenseur 1,20 x 0,60 x 0,20', 'CLIMATISEUR', 'forfait'),
  ('CLIM_GRILLE_PROTECTION_CONDENSEUR', 'Confection et remplacement de grille de protection de condenseur galvanisée au modèle', 'CLIMATISEUR', 'forfait'),
  ('CLIM_ETANCHEITE_SOCLE', 'Reprise d''étanchéité sur le socle en béton', 'CLIMATISEUR', 'forfait'),
  ('CUVE_TOLERIE_PEINTURE', 'Reprise de la tôlerie et peinture antirouille pour cuve', 'GE', 'forfait'),
  ('CUVE_REDEPLOIEMENT', 'Redéploiement de cuves', 'GE', 'forfait'),
  ('SOL_BOITE_JONCTION_PARAFOUDRE', 'Boîte de jonction avec parafoudre type I et type II', 'SOLAIRE', 'unité'),
  ('SOL_REGULATEUR_MPPT_48V', 'Régulateur MPPT 1+1 48V', 'SOLAIRE', 'unité'),
  ('SOL_ONDULEUR_CHARGEUR_4000_48', 'Onduleur-chargeur 4000-48, 500W AC en sortie', 'SOLAIRE', 'unité'),
  ('SOL_MODULES_MPPT_S48_2000', 'Modules solaires MPPT S48-2000', 'SOLAIRE', 'unité'),
  ('SOL_REDRESSEURS_R48_2000', 'Redresseurs R48-2000', 'SOLAIRE', 'unité'),
  ('SOL_PANNEAUX_CSUN300_72HM', 'Panneaux solaires CSUN300-72HM', 'SOLAIRE', 'unité'),
  ('SOL_CARTE_DEMARRAGE_GE_EMERSON', 'Carte de démarrage automatique des GE incorporés dans les systèmes hybrides (Emerson)', 'SOLAIRE', 'unité'),
  ('SOL_CONVERTISSEUR_STUDER_AJ700_48', 'Convertisseur STUDER AJ 700-48', 'SOLAIRE', 'unité'),
  ('SOL_CARTE_DEMARRAGE_GE_POWER_ONE', 'Carte de démarrage automatique des GE incorporés dans les systèmes hybrides (Power One)', 'SOLAIRE', 'unité'),
  ('BAT_CABLE_JONCTION_2V1500AH', 'Câble de jonction batteries 2V 1500 Ah', 'BATTERIE', 'unité'),
  ('BAT_COSSE_2V1500AH', 'Cosse batteries 2V 1500 Ah', 'BATTERIE', 'unité')
) AS v(code, libelle, categorie, unite)
WHERE NOT EXISTS (
  SELECT 1 FROM "pieces_ref" p
  WHERE p.code = v.code
     OR regexp_replace(lower(translate(p.libelle, 'ÀÂÄÉÈÊËÎÏÔÖÙÛÜÇàâäéèêëîïôöùûüç', 'AAAEEEEIIOOUUUCaaaeeeeiioouuuc')), '[^a-z0-9]', '', 'g')
      = regexp_replace(lower(translate(v.libelle, 'ÀÂÄÉÈÊËÎÏÔÖÙÛÜÇàâäéèêëîïôöùûüç', 'AAAEEEEIIOOUUUCaaaeeeeiioouuuc')), '[^a-z0-9]', '', 'g')
)
ON CONFLICT ("code") DO NOTHING;
